wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.9
    cli_version: 0.16.6
    framework: fastai
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1714904021.0
    t:
      1:
      - 1
      - 4
      - 5
      - 35
      - 41
      - 53
      - 55
      2:
      - 1
      - 4
      - 5
      - 35
      - 41
      - 53
      - 55
      3:
      - 23
      - 61
      4: 3.11.9
      5: 0.16.6
      8:
      - 4
      - 5
      13: darwin-arm64
direction:
  desc: null
  value:
  - MAXIMIZE
